version: '3.7'
services:
  builder:
    build: docker
    image: debian-builder:latest
    command: "bash -c 'cd /workspace && bash'"
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace:rw
    working_dir: /workspace
